version: "3"

x-networks: &networks
  networks:
    - house_marketplace_network

services:
  # frontend:
  #   <<: *networks
  #   build:
  #     context: frontend
  #   volumes:
  #     - hk_prod_node_modules:/app/node_modules
  #   environment:
  #     BACKEND_API_URL: http://backend:3003/api/v1
  #   ports:
  #     - 3000:3000
  backend:
    <<: *networks
    build:
      context: backend
    ports:
      - 3003:3003
    environment:
      PORT: 3003
      DATABASE_URL: postgres://house:house@db:5432/house_marketplace_development
      DEVISE_JWT_SECRET_KEY: e5f8d09c9c789fd5ace3edcf
      SECRET_KEY_BASE: a17a8c55233c5479f7820728845ea
    volumes:
      - hk_prod_rails_bundle:/usr/local/bundle

volumes:
  hk_prod_rails_bundle:
  hk_prod_node_modules:

networks:
  house_marketplace_network:
    external: true
